### PR TITLE
Release 3.1.0

### LINKED ISSUE #856: New release - 3.0.6?
Whats the plan on having another release?

Looking at the diff since the last release (https://github.com/jaagr/polybar/compare/3.0.5...master) there have been quite a few bug fixes that would nicely fit into another release. :-)

Also, NixOS is currently working on switching to gcc7 (https://github.com/NixOS/nixpkgs/issues/31747) where polybar currently fails building due to missing patches in the latest version.

### PR DESCRIPTION
**Pull request by patrick96**
This is a first draft for the polybar 3.1.0 release.

**Things to do before merging:**

- [x] Write changelog and add it to the github release tag
- [x] Check if all new features are documented on the wiki

**Things to do after this is merged:**

- [ ] Ensure AUR packages build properly and have proper version tags
- [ ] Push updated PKGBUILDs (and .SRCINFO)
- [ ] Inform other package maintainers of new version (https://repology.org/metapackage/polybar/versions)
- [ ]  Update Void Linux package
- [ ] Remove jsoncpp issue from "Known Issues" page

Please tell me, if you think there are other things that need to be done for this release.

Closes #856

### CODE REVIEW

**Comment by NBonaparte** [comment]
I recently found that #567 (which splits `format-online` into `format-playing`, `format-paused`, and `format-stopped`) breaks all `format-online-*` options (such as `format-online-background`). Should we fix this, or recommend users to apply the original settings to `-playing`, `-paused`, and `-stopped` (in the changelog perhaps)?

**Comment by patrick96** [comment]
Since this breaks existing configs, I think we should fix this first.
From what I can tell, the formatter doesn't support multiple inheritance and it just falls back to `format-bg` etc. instead of `format-online-*`:
https://github.com/jaagr/polybar/blob/1158d5d889fa9b4ed3a9ae36867ef2c45330f21b/src/modules/meta/base.cpp#L84-L97
For now, I think we should "manually" copy the `format-online-*` values to the other `format-(playing|paused|stopped)` settings. And for the next release we should probably think about allowing multiple inheritance.

**Comment by NBonaparte** [comment]
I've made a rough draft for the release notes, with breaking changes and a changelog. I only listed major outward-facing fixes and the main build issues along with their commits/PR and issues. Feel free to reformat it and/or add other things to the changelog.

**Comment by patrick96** [comment]
The changelog looks great, I have separated it into features and fixes for clarity. Gonna merge this once I confirm that all new features are documented on the wiki

**Pull request merged**
