### PR TITLE
[bspwm] Separate focused/unfocused state from occupation state

### PR DESCRIPTION
**Pull request by delehef**
Hello,

I like to keep the same icons whether a workspace is focused or not, but makes its color change; hence the following commit removing the `WORKSPACE_FOCUSED` flag and replacing it with `WORKSPACE_FOCUSED_{URGENT,EMPTY,OCCUPIED}`.

Do you like the idea?

### CODE REVIEW

**Comment by jaagr** [comment]
Hi and thanks for contributing. Yeah I think it allows for more specific configuration but I think we should add a `label-focused` parameter that the user could define to avoid having to set all 3 if they are all the same.

Could you also update the README to reflect the changes?

**Comment by delehef** [comment]
Indeed, that's a nice idea, I'll try to add it this evening

Cheers!

**Comment by delehef** [comment]
Well, the “evening” took a little bit more than I'd have liked it to, but now it should be OK.

**Comment by delehef** [comment]
Sorry to insist, bu t are you still interested in this PR?

**Comment by jaagr** [comment]
Yeah sorry for the delay... stuff keeps popping up. Will have a look once I'm settled with my current list.

**Comment by delehef** [comment]
No problem, I just wanted to know if you were still interested.

**Comment by jaagr** [comment]
Would you mind applying the changes to the new module? Can't merge since the file structure have changed.

**Comment by delehef** [comment]
Sent in a new PR.

**Comment by jaagr** [comment]
#201 has been merged

**Pull request closed without merging**
