### PR TITLE
fix(xcb): check for composite extension

### LINKED ISSUE #1425: polybar doesn't display in i3wm, gentoo
## Describe the issue
polybar doesn't display in X in gentoo amd64, i3-gaps and default config.

**Expected behavior:**

polybar would display

**Actual behavior:**

patrick96 also mentioned this seems similar to https://github.com/jaagr/polybar/issues/939

polybar doesn't display.  debugging with gdb it appears to be an xcb issue?:

renderer.cpp:83 cw_flush(true) is not returning in gdb
xcb_request_check(std::forward<Connection>(c), cookie); seems to be returning an error object
{response_type = 0 '\000', error_code = 8 '\b', sequence = 85, resource_id = 383, minor_code = 0, major_code = 1 '\001', pad0 = 0 '\000', pad = {0, 0, 0, 0, 0}, full_sequence = 85}

Error code 8 seems to mean BadMatch from what I googled.

setting cw_flush(false) progresses further but nothing is displayed.

This branch is being taken: polybar/lib/xpp/include/xpp/proto/../generic/request.hpp:37

What's also interesting is I see my monitor disconnecting then reconnecting in /var/log/Xorg.0.log when I start polybar:
```
[  2061.192] (--) NVIDIA(GPU-0): DFP-0: disconnected
[  2061.192] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[  2061.192] (--) NVIDIA(GPU-0): DFP-0: 165.0 MHz maximum pixel clock
[  2061.192] (--) NVIDIA(GPU-0):
[  2061.192] (--) NVIDIA(GPU-0): DFP-1: disconnected
[  2061.192] (--) NVIDIA(GPU-0): DFP-1: Internal TMDS
[  2061.192] (--) NVIDIA(GPU-0): DFP-1: 165.0 MHz maximum pixel clock
[  2061.192] (--) NVIDIA(GPU-0):
[  2061.192] (--) NVIDIA(GPU-0): LG Electronics LG Ultra HD (DFP-2): connected                                                               
[  2061.192] (--) NVIDIA(GPU-0): LG Electronics LG Ultra HD (DFP-2): Internal DisplayPort                                                    
[  2061.192] (--) NVIDIA(GPU-0): LG Electronics LG Ultra HD (DFP-2): 1440.0 MHz maximum pixel clock                                          
[  2061.192] (--) NVIDIA(GPU-0):
[  2061.195] (--) NVIDIA(GPU-0): DFP-3: disconnected
[  2061.195] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[  2061.195] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[  2061.195] (--) NVIDIA(GPU-0):
[  2061.195] (--) NVIDIA(GPU-0): DFP-4: disconnected
[  2061.195] (--) NVIDIA(GPU-0): DFP-4: Internal DisplayPort
[  2061.195] (--) NVIDIA(GPU-0): DFP-4: 1440.0 MHz maximum pixel clock
[  2061.195] (--) NVIDIA(GPU-0):
[  2061.195] (--) NVIDIA(GPU-0): DFP-5: disconnected
[  2061.195] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[  2061.195] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[  2061.195] (--) NVIDIA(GPU-0):
[  2088.288] (--) NVIDIA(GPU-0): DFP-0: disconnected
[  2088.288] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[  2088.288] (--) NVIDIA(GPU-0): DFP-0: 165.0 MHz maximum pixel clock
[  2088.288] (--) NVIDIA(GPU-0):
[  2088.288] (--) NVIDIA(GPU-0): DFP-1: disconnected
[  2088.288] (--) NVIDIA(GPU-0): DFP-1: Internal TMDS
[  2088.288] (--) NVIDIA(GPU-0): DFP-1: 165.0 MHz maximum pixel clock
[  2088.288] (--) NVIDIA(GPU-0):
[  2088.288] (--) NVIDIA(GPU-0): LG Electronics LG Ultra HD (DFP-2): connected                                                               
[  2088.288] (--) NVIDIA(GPU-0): LG Electronics LG Ultra HD (DFP-2): Internal DisplayPort                                                    
[  2088.288] (--) NVIDIA(GPU-0): LG Electronics LG Ultra HD (DFP-2): 1440.0 MHz maximum pixel clock                                          
[  2088.288] (--) NVIDIA(GPU-0):
[  2088.291] (--) NVIDIA(GPU-0): DFP-3: disconnected
[  2088.291] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[  2088.291] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[  2088.291] (--) NVIDIA(GPU-0):
[  2088.291] (--) NVIDIA(GPU-0): DFP-4: disconnected
[  2088.291] (--) NVIDIA(GPU-0): DFP-4: Internal DisplayPort
[  2088.291] (--) NVIDIA(GPU-0): DFP-4: 1440.0 MHz maximum pixel clock
[  2088.291] (--) NVIDIA(GPU-0):
[  2088.291] (--) NVIDIA(GPU-0): DFP-5: disconnected
[  2088.291] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[  2088.291] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[  2088.291] (--) NVIDIA(GPU-0):
```
## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
polybar 3.2.1 compiled from gentoo emerge.  Same thing happens with git version.
The example ini with battery and a few modules removed.
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
* Loading config: /home/uno/.config/polybar/config                                                                                                                                                          
- config: Copying missing params (sub="module/backlight-acpi", base="module/xbacklight")                                                                                                                         
- config: Current bar section: [bar/example]
* Loaded monitor DP-0 (3840x2160+0+0)                                                                                                                                                                            
* Bar geometry: 3840x35+0+0                                                                                                                                                                                      
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules
- module/powermenu: Creating menu level 0
- module/powermenu: Creating menu level item 0
- module/powermenu: Creating menu level item 1                                                                                                                                                                   
- module/powermenu: Creating menu level 1                                                                                                                                                                        
- module/powermenu: Creating menu level item 0
- module/powermenu: Creating menu level item 1
- module/powermenu: Creating menu level 2
- module/powermenu: Creating menu level item 0
- module/powermenu: Creating menu level item 1                                                                                                                                                                   
* Starting application                                                                                                                                                                                           
- controller: Main thread id = 1
* Starting module/i3
* Starting module/filesystem
* Starting module/alsa
- module/i3: Thread id = 2
* Starting module/xkeyboard
- module/filesystem: Thread id = 3                                                                                                                                                                               
* Starting module/memory                                                                                                                                                                                         
- module/alsa: Thread id = 4
- module/xkeyboard: Thread id = 5
* Starting module/cpu
* Starting module/temperature                                                                                                                                                                                    
- module/cpu: Thread id = 6                                                                                                                                                                                      
* Starting module/date                                                                                                                                                                                           
- module/temperature: Thread id = 7                                                                                                                                                                              
* Starting module/powermenu                                                                                                                                                                                      
- module/memory: Thread id = 8
* Entering event loop (thread-id=1)                                                                                                                                                                              
- module/date: Thread id = 9                                                                                                                                                                                     
- module/powermenu: Thread id = 10                                                                                                                                                                               
* Eventqueue worker (thread-id=11)                                                                                                                                                                               
- bar: Create renderer                                                                                                                                                                                           
- renderer: Get TrueColor visual                                                                                                                                                                                 
- renderer: Allocate colormap                                                                                                                                                                                    
- renderer: Allocate output window
# this is where cw_flush(true) is presumably failing
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`:

```polybar 3.2.1                                                                                                                                                                                                    

Features: +alsa -curl +i3 -mpd -network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: Gentoo
Compiler: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -pipe -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1 -Wl,--as-needed```

## Additional context
*Add any other context that you think is necessary about the problem here.*

### PR DESCRIPTION
**Pull request by NBonaparte**
Rendering doesn't work if the composite extension is disabled (confirmed by me and @Derynect), so we should check that it is enabled.

Fixes #1425

### CODE REVIEW

**Comment by patrick96** [comment]
For me the xcomposite extension is disabled by default and I can still render fine.
And from what I can see from the cmake logs in many of the issues here, it's disabled for everyone.

**Comment by NBonaparte** [comment]
I meant disabled in X11. We need to enable the composite extension in _polybar_ to check if the extension in _X11_ exists (which is usually the case).

**Comment by patrick96** [comment]
I'm having trouble reproducing this. For some reason I cannot disable the `Composite` X extensions, it prints the warning `Ignoring unrecognized extension "Composite"`, even though `xdpyinfo -queryExtensions` list it as enabled. I will try to reproduce it on my desktop, maybe I'll have more luck there.

I have seen that you needed to add a new dependency in travis for this. Is this an actual hard dependency that we have missed before?

**Comment by NBonaparte** [comment]
I had that problem too, apparently it had to be `"COMPOSITE"` (all caps).

It might be a new dependency, but most people already have it installed. On Arch it's a dependency of gtk, compton, and even xorg-xdpyinfo, which is why it's easy to miss. I guess on Gentoo it isn't set as a dependency of compton.

**Comment by patrick96** [comment]
I have added the packages providing xcb-composite to the wiki where necessary.

**Comment by NBonaparte** [comment]
Where does the xrandr extension throw an error while compiling?

**Comment by patrick96** [comment]
If you manually disable the randr extension (with `-DWITH_XRANDR=OFF`) [`x11/extensions/randr.hpp`](https://github.com/jaagr/polybar/blob/master/include/x11/extensions/randr.hpp) will hit `#error "X RandR extension is disabled..."`
Because the code cannot compile without randr, at least not in the current code base.

**Comment by NBonaparte** [comment]
I think that's only a catchall to make sure it shouldn't be compiled when it is accidentally included, because [`x11/extensions/all.hpp`](https://github.com/jaagr/polybar/blob/master/include/x11/extensions/all.hpp) should not include `randr.hpp` if `WITH_XRANDR=OFF`. [`composite.hpp`](https://github.com/jaagr/polybar/blob/master/include/x11/extensions/composite.hpp) already has the check as well.

**Comment by patrick96** [comment]
Even if you actually add that check to all inclusions of `randr.hpp`, you still get compiler errors like
```
/home/patrick96/Projects/github.com/patrick96/polybar/src/components/screen.cpp:60:16: error: ‘class polybar::v3_2_0_26_g11d66ee_git::connection’ has no member named ‘randr’
   m_connection.randr().select_input(m_proxy, XCB_RANDR_NOTIFY_MASK_SCREEN_CHANGE);
```
and a bunch more.

Here is the diff for that, if you want to try it yourself:
```diff
diff --git a/include/components/screen.hpp b/include/components/screen.hpp
index 04ae97f..6cea701 100644
--- a/include/components/screen.hpp
+++ b/include/components/screen.hpp
@@ -4,7 +4,9 @@
 #include "components/types.hpp"
 #include "events/signal_emitter.hpp"
 #include "events/signal_fwd.hpp"
+#if WITH_XRANDR
 #include "x11/extensions/randr.hpp"
+#endif
 #include "x11/types.hpp"
 #include "x11/window.hpp"
 
diff --git a/include/modules/xbacklight.hpp b/include/modules/xbacklight.hpp
index 8d6c257..29ab96e 100644
--- a/include/modules/xbacklight.hpp
+++ b/include/modules/xbacklight.hpp
@@ -5,7 +5,9 @@
 #include "modules/meta/event_handler.hpp"
 #include "modules/meta/input_handler.hpp"
 #include "modules/meta/static_module.hpp"
+#if WITH_XRANDR
 #include "x11/extensions/randr.hpp"
+#endif
 
 POLYBAR_NS
 
diff --git a/include/utils/bspwm.hpp b/include/utils/bspwm.hpp
index 075e256..996b326 100644
--- a/include/utils/bspwm.hpp
+++ b/include/utils/bspwm.hpp
@@ -7,7 +7,9 @@
 #include "settings.hpp"
 #include "utils/socket.hpp"
 #include "utils/string.hpp"
+#if WITH_XRANDR
 #include "x11/extensions/randr.hpp"
+#endif
 #include "x11/window.hpp"
 
 POLYBAR_NS
diff --git a/include/utils/i3.hpp b/include/utils/i3.hpp
index ae9f2e9..da6088d 100644
--- a/include/utils/i3.hpp
+++ b/include/utils/i3.hpp
@@ -3,7 +3,9 @@
 #include <i3ipc++/ipc.hpp>
 
 #include "common.hpp"
+#if WITH_XRANDR
 #include "x11/extensions/randr.hpp"
+#endif
 
 POLYBAR_NS
 
diff --git a/src/x11/window.cpp b/src/x11/window.cpp
index e22e445..5ee19f9 100644
--- a/src/x11/window.cpp
+++ b/src/x11/window.cpp
@@ -2,7 +2,9 @@
 #include "utils/memory.hpp"
 #include "x11/atoms.hpp"
 #include "x11/connection.hpp"
+#if WITH_XRANDR
 #include "x11/extensions/randr.hpp"
+#endif
 #include "x11/window.hpp"
 
 POLYBAR_NS
```

The whole codebase was built with randr in mind, it would take huge refactoring to be able to disable randr support, if it's even possible.

**Comment by NBonaparte** [comment]
So how should this be handled? Should we remove the flag entirely or keep it somewhat modular and just throw an error when not using the flag?

**Comment by patrick96** [comment]
I think it should be impossible to disable hard dependencies, since it will just fail either during compilation or runtime anyways, and I'd rather have an error during cmake.

So yeah, remove the flag, or probably better, make it immutable and fail cmake, if the library wasn't found. We probably still want to show it in the `settings.hpp` file, so we can't totally drop `WITH_XCOMPOSITE`.

We should try to separate hard and soft dependencies inside cmake anyway, so after this PR, we can use the same approach you used for xcb-composite for the other hard dependencies like xrandr.

**Comment by NBonaparte** [comment]
@patrick96 is this good enough?

**Pull request merged**
