### PR TITLE
Fix xkeyboard crashing when indicators where enabled

### LINKED ISSUE #1660: xkeyboard displaying incorrect information and crashing
## Describe the issue
I recompiled polybar from source today, and I noticed that the xkeyboard module is totally misbehaving. When I reloaded my polybar, I noticed that it showed I had both my Capslock and Scroll lock keys on, which I definitely did not (now that I think about it, k don't even have a scroll lock key). I tried pressing Capslock a few times, and polybar crashed. I tried again a few times, and it seemed that pressing Capslock a few times causes it to crash repeatedly.

**Expected behavior:**
Polybar's xkeyboard module should only show the Capslock and Scroll lock indicators when the respective keys are on. In addition, polybar should not crash when the caps lock key is hit a few times.

**Actual behavior:**
Polybar always shows the Capslock and Scroll lock indicators. In addition, it crashes when Capslock is hit a few times.

**Was it working before?**
I last compiled polybar from commit ca4426a9, which worked fine. Now, it fails on commit db9a83a8. (Curiously, this commit is about xkeyboard related stuff.)

## To Reproduce
My configuration is basically the stock example configuration. I haven't made any changes to xkeyboard. I will test out a sample MVE config tomorrow.

Launch polybar. Note Capslock and Scroll lock indicators. Press Capslock a few times. Note crash.

## Polybar Log
I will try to add this tomorrow.

## Screenshots
I will try to add this tomorrow.

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`: I will try to add this tomorrow.

### PR DESCRIPTION
**Pull request by patrick96**
Fixes #1660

### CODE REVIEW

**Comment by arjvik** [comment]
I just tested the PR out, and it works great! Thanks @patrick96 for fixing this so quickly!

**Comment by ddffnn** [comment]
Even when using `patrick96:issue/1660` polybar generates a segmentation fault when I use `format = <label-layout>` in module/xkeyboard. If I use `format = <label-name>` polybar runs without issue.

**Comment by ddffnn** [comment]
Just chiming in to say that [16a714a](https://github.com/jaagr/polybar/pull/1661/commits/16a714a9edbef3a73071269913f176efc6e284e8) fixed the seg fault for me. I use `format = <label-layout>`.

**Comment by patrick96** [comment]
@ddffnn This only occured to me because of the comment you posted (and then deleted?) :wink:

**Comment by ddffnn** [comment]
Well, I didn't get the crash when I used `format = <label-name>`, and I put that in my comment. Then I realized that `<label-name>` isn't even valid so the module didn't show up at all. I assumed that the seg fault didn't occur because I had essentially turned off the module. I deleted my comment because I thought it was just noise. I'm glad it wasn't!

**Comment by arjvik** [comment]
Wait I'm confused - with the new system, what should the format be? I compiled 2432a7e and tested that it works fine with (basically) the default config from a while back that I slightly tweaked. This is the same config that crashed db9a83a but worked on ca4426a.

Here is the relevant section of mine in case it is needed:
```dosini
[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}
```

**Comment by ddffnn** [comment]
The new feature that allows setting the icon based on the current layout doesn't seem to work for layout variants. I run `setxkbmap -layout dvorak,us` and have my xkeyboard module configured with `format = <label-layout>` and `label-layout = %name%`. Both dvorak and us have the same `%layout%` value (us) so I don't display it. This means that I can't have different icons selected for each variant. Maybe the icons should match against the `%name%` value?

**Comment by patrick96** [comment]
@arjvik The format should work as it always has, we didn't change anything there. This PR is only here to fix crashes that occured with valid formats. The supported values for `format` are listed on the [Wiki](https://github.com/jaagr/polybar/wiki/Module:-xkeyboard#additional-formatting)

@ddffnn This a PR to fix a bug. Please open feature requests as a new issue. You should tag Gilnaa who originally implemented this, maybe he can add this feature as well.

**Comment by arjvik** [comment]
When will this be merged?

**Comment by NBonaparte** [comment]
Now.

**Pull request merged**
