### PR TITLE
Release 3.2.0

### PR DESCRIPTION
**Pull request by patrick96**
I think the 3.2.0 release is badly needed right now, for one because xcb-proto 1.13 is getting more and more common, making the 'eventstruct' issue (#973) catch on (see #1335, #1330, #1294, #1252, #1233, #1090, #1114) and also 3.1.0 cannot be compiled with gcc 8 without manually updating the i3ipcpp submodule.

The [3.2.0 Milestone](https://github.com/jaagr/polybar/milestone/2) contained quite a few unfinished issues, I have moved almost all of them into the [3.3.0 Milestone](https://github.com/jaagr/polybar/milestone/4) because this release now has some urgency to it.
The only issue I kept was #1194, because there is already a fix for it (#1198), it just needs to be reviewed and merged.

With this release, I'd like to also propose some guidelines on how we do releases. The base idea is that each minor (and major) release (like 3.0.0, 3.1.0, 3.2.0, etc) gets its own branch. The name of the branch is the version number with the patch number dropped (e.g. 3.2, 4.0, etc) so that we don't get any conflicts with the git tags for the versions (that's why in the README I used `--branch 3.2`). Development continues on `master`, no actual work is done directly in the release branches. If we need to release a patch version (e.g. 3.2.1), for example because of a critical bug, we cherry-pick the commit that fixes the bug onto the current release branch (*Note:* The 3.2.1 tag is only present in the release branch, the `master` branch now only contains the tags for minor and major releases). So we basically backport the fixes, this way we don't have to create minor releases for every bug, just because we implemented a feature in the meantime. It also prevents the behaviour we have now, where we have to patch up the PKGBUILDs and write extra instructions just to get the current version to compile.

I'd like to get your feedback on these release guidelines, if you approve, I will write a page on the wiki with a release protocol.

**Things to do before merging:**
- [x] Write changelog and add it to the github release tag
- [x] Check if all new features are documented on the wiki

**Things to do after this is merged:**
- [ ] Remove `(unreleased)` note from new features in the wiki
- [ ] Create the `3.2` branch with this PR as its base commit.
- [ ] Publish drafted release with target on the `3.2` branch
- [ ] Ensure AUR packages build properly and have proper version tags
- [ ] Push updated PKGBUILDs (and .SRCINFO)

@NBonaparte could you please review #1198 so that we can fix that bug for this release.

### CODE REVIEW

**Comment by NBonaparte** [comment]
Sounds good.

It might also be nicer to do more frequent minor releases because we usually end up having a large backlog of features, fixes, etc. We should have some metric to determine when to release, especially if some PRs in the milestone take longer than expected.

**Comment by patrick96** [comment]
I agree, we should maybe limit our milestones to 5 or 6 features and if they're done, just do a release. If only one of them is holding the others back, we just move it to the next milestone and continue with the release.

**Comment by patrick96** [comment]
Will try to finally release this thing tomorrow and nicely write up the release guidelines.

**Comment by patrick96** [comment]
I have written down the [guidelines](https://github.com/jaagr/polybar/wiki/Release-Guidelines) in the wiki, if you want to read them

**Pull request merged**
