### PR TITLE
feat(xworkspaces): List occupied workspaces

### PR DESCRIPTION
**Pull request by swillner**
Fixes issues in #882

### CODE REVIEW

**Comment by kronn** [comment]
may I cherry-pick your change into my PR, @swillner? Then the whole history is in one place. attribution should stay the same...

**Comment by swillner** [comment]
of course! just give me a ping and I'll close this PR.

**Comment by kronn** [comment]
> of course! just give me a ping and I'll close this PR.

There is no ping-emoji, but I can give you :ping_pong:. Completely unrelated, I cherry-picked your fix and added it to the other PR. :-)

**Comment by swillner** [comment]
thanks!

**Pull request closed without merging**
