### PR TITLE
Add support for left and right "ends" to (mpd) progress bars

### PR DESCRIPTION
**Pull request by mrkgnao**
Basically, doing this:

```
bar-progress-left = [
bar-progress-fill = ─
bar-progress-indicator = 
bar-progress-empty = " "
bar-progress-right = ]
```

gets you [this](https://u.teknik.io/WRw5E.png).

I don't think this can be merged as it is, since currently the `bar-progress-(left|right)` options are required, and I'll get that fixed ASAP.

### CODE REVIEW

**Comment by jaagr** [comment]
I can't load the linked image

**Comment by mrkgnao** [comment]
Whoops. Essentially, you get something like 

    [----------                ]

**Comment by patrick96** [comment]
Can't this be achieved by doing this: `format-online = [<bar-progress>]`?

**Comment by NBonaparte** [comment]
@patrick96 I believe so. Closing.

**Pull request closed without merging**
