### PR TITLE
fix(cpu): Replace %percentage-cores% normally

### LINKED ISSUE #1282: %percentage-cores does not support min-width.
Hey!

I cannot seem to get the min-width syntax working with the %percentage-cores% token.

```ini
[module/cpu]
type = internal/cpu

label = %percentage-cores:4%
```
Just results in `%percentage-cores%` in the bar.

### PR DESCRIPTION
**Pull request by TonCherAmi**
Resolves #1282 

This pretty much restores the way things were done pre 3292cea where the token splitting shenanigans were introduced.

### CODE REVIEW

**Comment by patrick96** [comment]
Shouldn't the min-width property be applied to each core percentage individually instead of to the whole token? When it was a compound token that interpretation made the most sense to me, that's why I initially thought this PR didn't really fix the issue.

**Comment by TonCherAmi** [comment]
I don't believe it should. In my opinion that goes against the way tokens are normally expected to work, the implementation is also rather hackish as a result. Furthermore it would make it impossible to set max-width of the token, whereas the behavior you describe is still achievable using individual `%percentage-corex%` tokens.

**Comment by TonCherAmi** [comment]
I do agree however that the behavior you describe would be pretty nice to have in this case. Perhaps we could introduce some kind of new syntax for this sort of thing, e.g. `[%percentage-cores%]` or something like that. We could then deprecate `%percentage-cores%` afterwards.

**Comment by patrick96** [comment]
@NBonaparte what do you think?
I think `%percentage-cores%` should be regarded as a compound token and pass on all its token properties to the `%percentage-coreX%` tokens.

**Comment by NBonaparte** [comment]
I suppose that is more logical. @TonCherAmi's suggestion also makes sense since right now compound tokens don't have different syntax, so it could be confusing.

**Comment by patrick96** [comment]
`%percentage-cores%` is the only compound token in polybar and I can't think of any other situation where a compound token would make sense. Introducing new syntax for just this token seems a bit much to me. As long as it is documented properly this shouldn't create any problems.

**Pull request merged**
