### PR TITLE
docs: Add xcb cursor dependency to README

### PR DESCRIPTION
**Pull request by patrick96**

### CODE REVIEW

**Comment by NBonaparte** [comment]
IIRC I made `xcb-util-cursor` an optional dependency; should it be changed to a required dependency?

**Comment by patrick96** [comment]
Technically it is optional because the functionality is turned off, if the macro is not set when building. But for example in the `PKGBUILD` `xcb-util-cursor` is a regular dependency. Do you think I should specifically mention that it is optional in the README?

**Comment by NBonaparte** [comment]
It probably should be listed as optional to reflect the code.

**Comment by patrick96** [comment]
I will add an optional dependencies section

**Comment by patrick96** [comment]
I did a force push. Have a look at it and merge, if you think everything is in order.

**Pull request merged**
