### PR TITLE
Fix difference between real and displayed value in backlight module

### LINKED ISSUE #1180: Backlight not updating correctly
When I change my brightness, it looks like polybar is updating the stored value, but not actually printing it until I change the brightness again. This results in a value that is behind by an update.

Say, if my brightness is 45%. I increment it by 5%, and I see my screen get brighter. However, the value stays at 45%. 
brightness(+5%) = Actual: 55%, Polybar: 50%
brightness(+5%) = Actual: 60%, Polybar: 55%
brightness(-20%) = Actual: 40%, Polybar: 60%
brightness(+10%) = Actual: 50%, Polybar 40%

Restarting polybar prints the correct value.

I am running a Lenovo Yoga 2 Pro on Fedora 27. 
I'm using internal/backlight, because xbacklight is not supported on my system. 
`card = intel_backlight`
I have a bash script that updates `/sys/class/backlight/intel_backlight/brightness` with an x% change, bound to function keys via i3

This is pretty unimportant, but it's a silly bug and I figured I'd file an issue. I may try digging through the source to resolve this after I'm finished setting up this laptop.

### PR DESCRIPTION
**Pull request by Lomadriel**
Fix #1180.

WARNING :warning: :warning: : This PR is not only a bugfix, it also add a new feature in polybar :arrow_right: udev meta module.

As explained in #1180. Inotify event aren't guaranteed to work on sysfs (/sys/ /proc/ /dev/ …). So we can't use inotify to watch in theses directories. (citation of the man page below)

> Inotify reports only events that a user-space program triggers through the filesystem API. As a result, it does not catch remote events that occur on network filesystems. (Applications must fall back to polling the filesystem to catch such events.) Furthermore, various pseudo-filesystems such as /proc, /sys, and /dev/pts are not monitorable with inotify.

So as the man said, the filesystem can be polled to catch such events, but there is an API to monitor device :arrow_right: udev.
~~Since udev is quite "standard" among linux distributions and freebsd, I don't think this dependency will cause any problem.~~

~~If polybar uses this API, it could be easy to solve #469 #839 #1046 #1181 that may be linked to the aforementioned problem with inotify.~~

EDIT: To fix the power problems, it is more UPower that should be used (with dbus) sorry my bad.

### CODE REVIEW

**Comment by Lomadriel** [comment]
I will fix this without using UDev.

**Comment by patrick96** [comment]
We may be able to use this udev implementation in other places in the future ;)

**Comment by Lomadriel** [comment]
> We may be able to use this udev implementation in other places in the future ;)

Yeap, but we will need to separate OS implementation since FreeBSD doesn't support UDev (we must use devd).
But using UDev and devd may should several problems in polybar.

**Comment by patrick96** [comment]
Once we have a solid interface for separating data collection from the part that formats it (#1529), we could tackle this.

**Pull request closed without merging**
