### PR TITLE
Support double-clicks in custom/script.

### PR DESCRIPTION
**Pull request by dkasak**
This adds support for double-click handlers in the custom/script module
(for all buttons; left, right and middle).

### CODE REVIEW

**Comment by patrick96** [comment]
Weird that this wasn't a feature before. Will try to take a look it in the next few days

**Comment by patrick96** [comment]
Does this work on your machine? I can't get it to work on mine.

**Comment by dkasak** [comment]
It did work when I wrote it, yes. I'll have to re-check whether something broke in the meantime.

**Comment by dkasak** [comment]
I rebased this on top of the current master and recompiled. It does work for me.

**Comment by patrick96** [comment]
The polybar double click handler doesn't seem to work well in general, so we need to do some fixing there. But the PR generates the correct action tags, so nothing wrong there.

**Pull request merged**
