### PR TITLE
feat(script): %pid% token for tail commands

### PR DESCRIPTION
**Pull request by patrick96**
This can be used to send signals to the script running (e.g. SIGUSR1, etc) which
makes it easier to have an updatable state inside the script. With this, it is
for example possible to have a two-state date script:
```dosini
[module/date]
type = custom/script
exec = /path/to/date.sh
tail = true
click-left = bash -c "kill -SIGUSR1 %pid%"
```

`date.sh`:
```bash

t=0

toggle() {
    t=$(((t + 1) % 2))
}


trap "toggle" USR1

while true; do
    if [ $t -eq 0 ]; then
        date
    else
        date --rfc-3339=seconds
    fi
    sleep 1 &
    wait
done
```
Todo:
- [ ]  Add to wiki

### CODE REVIEW

**Comment by NBonaparte** [comment]
Not exactly relevant to this PR specifically but is Travis having some issues? The clang build failed here as well as for #931 and I had to restart the builds for it to pass.

**Comment by patrick96** [comment]
I've had it once before where the travis build would suddenly fail for no reason. I think it's just a minor hickup.

**Comment by NBonaparte** [comment]
Does this fix #720?

**Comment by patrick96** [comment]
> Does this fix #720?

No, it only adds a new token to the script module click commands nothing else. The output of a click command can still not be used inside the bar. However this makes it easier to notify a tail command about a click event, whereas before we would have to write to a certain file to share information with a tailed script.

**Comment by NBonaparte** [comment]
I put the example in the wiki as part of the examples section.

**Pull request merged**
