### PR TITLE
Option to disable click to mute in alsa and pulseaudio modules

### LINKED ISSUE #1521: Disable mute on click
## Describe the issue
I have spent the last hour looking for a way to disable the mute on click functionality of the volume and alsa modules. I don't need it to ever be muted via the bar so I would like to disable it while still maintaining the ability to click on the workspace icons.

**Expected behavior:**

I click on the volume modules bar and nothing happens, or if possible it moves the volume level to the approximate point in the bar, though I doubt that is possible.

**Actual behavior:**

It mutes my master volume and requires manual unmuting.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/alsa]
    type = internal/alsa
    master-mixer = Master
    master-soundcard = hw:1
    ;click-left = ?
    interval = 5
    mapped = true

    format-volume = <bar-volume> <label-volume>
    label-muted = Muted
    label-muted-foreground = #689d6a
    label-volume-foreground = #689d6a

    bar-volume-width = 10
    bar-volume-foreground-0 = #aaff77
    bar-volume-foreground-1 = #aaff77
    bar-volume-foreground-2 = #fba922
    bar-volume-foreground-3 = #ff5555
    bar-volume-indicator = |
    bar-volume-indicator-foreground = #ff
    bar-volume-indicator-font = 3
    bar-volume-fill = ─
    bar-volume-fill-font = 3
    bar-volume-empty = ─
    bar-volume-empty-font = 3
    bar-volume-empty-foreground = #444444
```

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`:

polybar 3.1.0-161-g028b141

Features: +alsa +curl +i3 +mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags:

### PR DESCRIPTION
**Pull request by Deedone**
Option is called click-to-mute. Fixes #1521

### CODE REVIEW

**Comment by patrick96** [comment]
Hey, thank you very much for this. Codewise everything looks good and normally I would merge this, but as I already mentioned in #1521 I have written a concept for giving users more fine-grained control over click actions (see #1524). Implementing these changes would make this PR obsolete. Also there is a key `handle-events` that you can set to `false` and both the pulse and alsa modules will disable all click actions.

Sorry that this didn't work out.

**Comment by Deedone** [comment]
Thanks for your responce, I understand this situation. So can you suggest issues that are not very hard but need some work on?

**Comment by patrick96** [comment]
Yeah, sure. I think the only actionable bug that is also probably quite easy to fix is #975. There the i3 modules assumes in some places that the `m_statelabels` map is filled.

Other than that we have a some issues where we need help reproducing the issues and figuring out if/where the code goes wrong:
* #743: The filesystem module shows weird values. Most likely an integer overflow/underflow.
* #991: Some fontawesome characters are cut off when rendering with certain font sizes. This one's probably quite tough to track down

There are more but I think those two are the ones where you can actually get results.

**Comment by awsms** [comment]
> Hey, thank you very much for this. Codewise everything looks good and normally I would merge this, but as I already mentioned in #1521 I have written a concept for giving users more fine-grained control over click actions (see #1524). Implementing these changes would make this PR obsolete. Also there is a key `handle-events` that you can set to `false` and both the pulse and alsa modules will disable all click actions.
> 
> Sorry that this didn't work out.

Is it possible to override the click behaviour of built-in modules?

**Pull request closed without merging**
